# rda Platform Support
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_PCM)  	+= rda_pcm.o
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_PCM)  	+= rda_dsp_aud.o
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_PCM)  	+= rda_voice_pcm.o
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_PCM)  	+= rda_audifc.o

obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_DAI)  	+= rda_dai.o
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_DAI)  	+= rda_voice_dai.o
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_CODEC)	+= rda_codec.o
obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD_CODEC)	+= rda_voice_codec.o

obj-$(CONFIG_SND_RDA_SOC_RDASOUNDCARD)	    	+= rda_soundcard.o
