#ifndef __ASM_ARCH_RDA_IOMAP_RDA8850E_H
#define __ASM_ARCH_RDA_IOMAP_RDA8850E_H

#include <asm/sizes.h>

/*
 * RDA8850E internal I/O mappings
 *
 * We have the following mapping:
 *      phys            virt
 *      00100000        FA000000
 *      20000000        FA000000 + sizeof(pre_io_space)
 *      others...
 *
 */

#define	RDA_IO_BASE           0xFA000000
/*
 * no need remap from AP
 */
#define RDA_SRAM_BASE         (RDA_IO_BASE)
#define RDA_SRAM_PHYS         0x00100000
#define RDA_SRAM_SIZE         SZ_64K

#define RDA_MD_MAILBOX_PHYS   0x00200000
#define RDA_MD_MAILBOX_SIZE   SZ_8K

#define RDA_MODEM_BASE        0x10000000
#define RDA_MODEM_SIZE        SZ_256M

#define RDA_MD_SYSCTRL_PHYS   0x11A00000
#define RDA_MD_SYSCTRL_SIZE   SZ_4K

#define RDA_MODEM_CLOCK_PHYS  0x11A02000
#define RDA_MODEM_CLOCK_SIZE  SZ_4K

#define RDA_RTC_PHYS          0x11A06000
#define RDA_RTC_SIZE          SZ_4K

#define RDA_CONFIG_REGS_PHYS  0x11A09000
#define RDA_CONFIG_REGS_SIZE  SZ_4K

#define RDA_MODEM_COM_PHYS    0x11A0A000
#define RDA_MODEM_COM_SIZE    SZ_4K

#define RDA_MODEM_SPI2_AP_PHYS 0x11A14000
#define RDA_MODEM_SPI2_AP_SIZE SZ_4K

#define RDA_MODEM_EBC_BASE    (RDA_SRAM_BASE + RDA_SRAM_SIZE)
#define RDA_MODEM_EBC_PHYS    0x11A03000
#define RDA_MODEM_EBC_SIZE    SZ_4K

#define RDA_MODEM_BCPU_BASE   (RDA_MODEM_EBC_BASE + RDA_MODEM_EBC_SIZE)
#define RDA_MODEM_BCPU_PHYS   0x11909000
#define RDA_MODEM_BCPU_SIZE   SZ_4K

#define RDA_MODEM_XCPU_BASE   (RDA_MODEM_BCPU_BASE + RDA_MODEM_BCPU_SIZE)
#define RDA_MODEM_XCPU_PHYS   0x11A16000
#define RDA_MODEM_XCPU_SIZE   SZ_4K

/* AHB0/AHB1, no pre-map */
#define RDA_CAMERA_PHYS       0x20000000
#define RDA_CAMERA_SIZE       SZ_256K

#define RDA_GOUDA_MEM_PHYS    0x20040000
#define RDA_GOUDA_MEM_SIZE    SZ_256K

#define RDA_VOC_PHYS          0x200C0000
#define RDA_VOC_SIZE          SZ_256K

#define RDA_USB_PHYS          0x20400000
#define RDA_USB_SIZE          SZ_256K

#define RDA_SPIFLASH_PHYS     0x20440000
#define RDA_SPIFLASH_SIZE     SZ_256K

#define RDA_ETHMAC_PHYS       0x20480000
#define RDA_ETHMAC_SIZE       SZ_256K

/* APB0 */
#define RDA_INTC_BASE         (RDA_MODEM_XCPU_BASE + RDA_MODEM_XCPU_SIZE)
#define RDA_INTC_PHYS         0x20800000
#define RDA_INTC_SIZE         SZ_4K

#define RDA_IMEM_BASE         (RDA_INTC_BASE + RDA_INTC_SIZE)
#define RDA_IMEM_PHYS         0x20810000
#define RDA_IMEM_SIZE         SZ_4K

#define RDA_DMA_BASE          (RDA_IMEM_BASE + RDA_IMEM_SIZE)
#define RDA_DMA_PHYS          0x20820000
#define RDA_DMA_SIZE          SZ_4K

#define RDA_VPU_BASE          (RDA_DMA_BASE + RDA_DMA_SIZE)
#define RDA_VPU_PHYS          0x20830000
#define RDA_VPU_SIZE          SZ_4K

#define RDA_GOUDA_BASE        (RDA_VPU_BASE + RDA_VPU_SIZE)
#define RDA_GOUDA_PHYS        0x20840000
#define RDA_GOUDA_SIZE        SZ_4K

#define RDA_CAMERA_DMA_BASE   (RDA_GOUDA_BASE + RDA_GOUDA_SIZE)
#define RDA_CAMERA_DMA_PHYS   0x20850000
#define RDA_CAMERA_DMA_SIZE   SZ_4K

#define RDA_LCDC_BASE   (RDA_CAMERA_DMA_BASE + RDA_CAMERA_DMA_SIZE)
#define RDA_LCDC_PHYS   0x20860000
#define RDA_LCDC_SIZE   SZ_4K

#define RDA_GPU_MALI_BASE     (RDA_LCDC_BASE + RDA_LCDC_SIZE)
#define RDA_GPU_MALI_PHYS     0x20870000
#define RDA_GPU_MALI_SIZE     SZ_64K

#define RDA_VPU_JPEG_BASE     (RDA_GPU_MALI_BASE + RDA_GPU_MALI_SIZE)
#define RDA_VPU_JPEG_PHYS     0x20890000
#define RDA_VPU_JPEG_SIZE     SZ_64K

#define RDA_CPU_DEBUG_BASE    (RDA_VPU_JPEG_BASE + RDA_VPU_JPEG_SIZE)
#define RDA_CPU_DEBUG_PHYS    0x208C0000
#define RDA_CPU_DEBUG_SIZE    SZ_64K
/* APB1 */
#define RDA_SYSCTRL_BASE      (RDA_CPU_DEBUG_BASE + RDA_CPU_DEBUG_SIZE)
#define RDA_SYSCTRL_PHYS      0x20900000
#define RDA_SYSCTRL_SIZE      SZ_4K

/* Os general timer */
#define RDA_TIMER_BASE        (RDA_SYSCTRL_BASE + RDA_SYSCTRL_SIZE)
#define RDA_TIMER_PHYS        0x20910000
#define RDA_TIMER_SIZE        SZ_4K

/* Core0 timer */
#define RDA_TIMER1_BASE       (RDA_TIMER_BASE + RDA_TIMER_SIZE)
#define RDA_TIMER1_PHYS        0x20911000
#define RDA_TIMER1_SIZE        SZ_4K

/* System counter used by A7 */
#define RDA_SYS_CNT_BASE       (RDA_TIMER1_BASE + RDA_TIMER1_SIZE)
#define RDA_SYS_CNT_PHYS        0x20912000
#define RDA_SYS_CNT_SIZE        SZ_4K

/* Reserved mapping */
#define RDA_RES0_BASE       (RDA_SYS_CNT_BASE + RDA_SYS_CNT_SIZE)
#define RDA_RES0_PHYS        0x20913000
#define RDA_RES0_SIZE        (SZ_64K - SZ_12K)

#define RDA_KEYPAD_BASE       (RDA_RES0_BASE + RDA_RES0_SIZE)
#define RDA_KEYPAD_PHYS       0x20920000
#define RDA_KEYPAD_SIZE       SZ_4K

#define RDA_GPIOA_BASE        (RDA_KEYPAD_BASE + RDA_KEYPAD_SIZE)
#define RDA_GPIOA_PHYS        0x20930000
#define RDA_GPIOA_SIZE        SZ_4K

#define RDA_GPIOB_BASE        (RDA_GPIOA_BASE + RDA_GPIOA_SIZE)
#define RDA_GPIOB_PHYS        0x20931000
#define RDA_GPIOB_SIZE        SZ_4K

#define RDA_GPIOD_BASE        (RDA_GPIOB_BASE + RDA_GPIOB_SIZE)
#define RDA_GPIOD_PHYS        0x20932000
#define RDA_GPIOD_SIZE        SZ_4K

#define RDA_GPIOE_BASE        (RDA_GPIOD_BASE + RDA_GPIOD_SIZE)
#define RDA_GPIOE_PHYS        0x20933000
#define RDA_GPIOE_SIZE        SZ_4K

/* Reserved in gpio space */
#define RDA_RES1_BASE        (RDA_GPIOE_BASE + RDA_GPIOE_SIZE)
#define RDA_RES1_PHYS        0x20934000
#define RDA_RES1_SIZE        (SZ_64K - SZ_16K)

#define RDA_GPIOC_BASE        (RDA_RES1_BASE + RDA_RES1_SIZE)
#define RDA_GPIOC_PHYS        0x11A08000
#define RDA_GPIOC_SIZE        SZ_4K

#define RDA_PWM_BASE          (RDA_GPIOC_BASE + RDA_GPIOC_SIZE)
#define RDA_PWM_PHYS          0x20940000
#define RDA_PWM_SIZE          SZ_4K

/* Reserved mapping */
#define RDA_RES2_BASE      (RDA_PWM_BASE + RDA_PWM_SIZE)
#define RDA_RES2_PHYS      0x20950000
#define RDA_RES2_SIZE      SZ_64K

#define RDA_TV_CTRL_BASE      (RDA_RES2_BASE + RDA_RES2_SIZE)
#define RDA_TV_CTRL_PHYS      0x20960000
#define RDA_TV_CTRL_SIZE      SZ_64K

/* Reserved mapping */
#define RDA_RES3_BASE      (RDA_TV_CTRL_BASE + RDA_TV_CTRL_SIZE)
#define RDA_RES3_PHYS      0x20970000
#define RDA_RES3_SIZE      SZ_64K

#define RDA_COMREGS_BASE      (RDA_RES3_BASE + RDA_RES3_SIZE)
#define RDA_COMREGS_PHYS      0x20980000
#define RDA_COMREGS_SIZE      SZ_4K

#define RDA_DMC400_BASE       (RDA_COMREGS_BASE + RDA_COMREGS_SIZE)
#define RDA_DMC400_PHYS       0x20990000
#define RDA_DMC400_SIZE       SZ_4K

#define RDA_DMC_PAGESPY_BASE       (RDA_DMC400_BASE + RDA_DMC400_SIZE)
#define RDA_DMC_PAGESPY_PHYS       0x20991000
#define RDA_DMC_PAGESPY_SIZE       SZ_4K

/* Reserved mapping */
#define RDA_RES4_BASE       (RDA_DMC_PAGESPY_BASE + RDA_DMC_PAGESPY_SIZE)
#define RDA_RES4_PHYS       0x20992000
#define RDA_RES4_SIZE       (SZ_64K - SZ_8K)

#define RDA_DDRPHY_BASE       (RDA_RES4_BASE + RDA_RES4_SIZE)
#define RDA_DDRPHY_PHYS       0x209A0000
#define RDA_DDRPHY_SIZE       SZ_4K

#define RDA_PD_CTRL_BASE       (RDA_DDRPHY_BASE + RDA_DDRPHY_SIZE)
#define RDA_PD_CTRL_PHYS       0x209B0000
#define RDA_PD_CTRL_SIZE       SZ_64K

/* Reserved mapping */
#define RDA_RES5_BASE       (RDA_PD_CTRL_BASE + RDA_PD_CTRL_SIZE)
#define RDA_RES5_PHYS       0x209C0000
#define RDA_RES5_SIZE       SZ_64K

#define RDA_AIF2_BASE         (RDA_RES5_BASE + RDA_RES5_SIZE)
#define RDA_AIF2_PHYS         0x209D0000
#define RDA_AIF2_SIZE         SZ_4K

#define RDA_AIF_BASE          (RDA_AIF2_BASE + RDA_AIF2_SIZE)
#define RDA_AIF_PHYS          0x209E0000
#define RDA_AIF_SIZE          SZ_4K

#define RDA_AUIFC_BASE        (RDA_AIF_BASE + RDA_AIF_SIZE)
#define RDA_AUIFC_PHYS        0x209F0000
#define RDA_AUIFC_SIZE        SZ_4K

/* APB2 */
#define RDA_UART1_BASE        (RDA_AUIFC_BASE + RDA_AUIFC_SIZE)
#define RDA_UART1_PHYS        0x20A00000
#define RDA_UART1_SIZE        SZ_4K

#define RDA_UART2_BASE        (RDA_UART1_BASE + RDA_UART1_SIZE)
#define RDA_UART2_PHYS        0x20A10000
#define RDA_UART2_SIZE        SZ_4K

#define RDA_SPI1_BASE         (RDA_UART2_BASE + RDA_UART2_SIZE)
#define RDA_SPI1_PHYS         0x20A20000
#define RDA_SPI1_SIZE         SZ_4K

#define RDA_SPI2_BASE         (RDA_SPI1_BASE + RDA_SPI1_SIZE)
#define RDA_SPI2_PHYS         0x20A30000
#define RDA_SPI2_SIZE         SZ_4K

#define RDA_SPI3_BASE         (RDA_SPI2_BASE + RDA_SPI2_SIZE)
#define RDA_SPI3_PHYS         0x20A40000
#define RDA_SPI3_SIZE         SZ_4K

#define RDA_SDMMC1_BASE       (RDA_SPI3_BASE + RDA_SPI3_SIZE)
#define RDA_SDMMC1_PHYS       0x20A50000
#define RDA_SDMMC1_SIZE       SZ_4K

#define RDA_SDMMC2_BASE       (RDA_SDMMC1_BASE + RDA_SDMMC1_SIZE)
#define RDA_SDMMC2_PHYS       0x20A60000
#define RDA_SDMMC2_SIZE       SZ_4K

#define RDA_SDMMC3_BASE       (RDA_SDMMC2_BASE + RDA_SDMMC2_SIZE)
#define RDA_SDMMC3_PHYS       0x20A70000
#define RDA_SDMMC3_SIZE       SZ_4K

#define RDA_NAND_BASE         (RDA_SDMMC3_BASE + RDA_SDMMC3_SIZE)
#define RDA_NAND_PHYS         0x20A80000
#define RDA_NAND_SIZE         SZ_16K

#define RDA_UART3_BASE        (RDA_NAND_BASE + RDA_NAND_SIZE)
#define RDA_UART3_PHYS        0x20A90000
#define RDA_UART3_SIZE        SZ_4K

#define RDA_GIC_BASE          (RDA_UART3_BASE + RDA_UART3_SIZE)
#define RDA_GIC_PHYS          0x20970000
#define RDA_GIC_SIZE          SZ_64K

#define RDA_I2C1_BASE         (RDA_GIC_BASE + RDA_GIC_SIZE)
#define RDA_I2C1_PHYS         0x20AB0000
#define RDA_I2C1_SIZE         SZ_4K

#define RDA_I2C2_BASE         (RDA_I2C1_BASE + RDA_I2C1_SIZE)
#define RDA_I2C2_PHYS         0x20AC0000
#define RDA_I2C2_SIZE         SZ_4K

#define RDA_I2C3_BASE         (RDA_I2C2_BASE + RDA_I2C2_SIZE)
#define RDA_I2C3_PHYS         0x20AD0000
#define RDA_I2C3_SIZE         SZ_4K

#define RDA_UART4_BASE        (RDA_I2C3_BASE + RDA_AUIFC_SIZE)
#define RDA_UART4_PHYS        0x20AE0000
#define RDA_UART4_SIZE        SZ_4K

#define RDA_IFC_BASE          (RDA_UART4_BASE + RDA_I2C3_SIZE)
#define RDA_IFC_PHYS          0x20AF0000
#define RDA_IFC_SIZE          SZ_4K

#endif /* __ASM_ARCH_RDA_IOMAP_RDA8850E_H */
