#ifndef __ASM_ARCH_IRQS_RDA8850E_H
#define __ASM_ARCH_IRQS_RDA8850E_H

#define RDA_IRQ_BASE       (32)

#define RDA_IRQ_SPI_BASE       (32)

#define RDA_IRQ_I2C            (RDA_IRQ_BASE + 0)
#define RDA_IRQ_NAND_NFSC      (RDA_IRQ_BASE + 1)
#define RDA_IRQ_SDMMC1         (RDA_IRQ_BASE + 2)
#define RDA_IRQ_SDMMC2         (RDA_IRQ_BASE + 3)
#define RDA_IRQ_SDMMC3         (RDA_IRQ_BASE + 4)
#define RDA_IRQ_SPI1           (RDA_IRQ_BASE + 5)
#define RDA_IRQ_SPI2           (RDA_IRQ_BASE + 6)
#define RDA_IRQ_SPI3           (RDA_IRQ_BASE + 7)
#define RDA_IRQ_UART1          (RDA_IRQ_BASE + 8)
#define RDA_IRQ_UART2          (RDA_IRQ_BASE + 9)
#define RDA_IRQ_UART3          (RDA_IRQ_BASE + 10)
#define RDA_IRQ_GPIO1          (RDA_IRQ_BASE + 11)
#define RDA_IRQ_GPIO2          (RDA_IRQ_BASE + 12)
#define RDA_IRQ_GPIO3          (RDA_IRQ_BASE + 13)
#define RDA_IRQ_KEYPAD         (RDA_IRQ_BASE + 14)
#define RDA_IRQ_TIMER          (RDA_IRQ_BASE + 15)
#define RDA_IRQ_TIMEROS        (RDA_IRQ_BASE + 16)
#define RDA_IRQ_COMREG0        (RDA_IRQ_BASE + 17)
#define RDA_IRQ_COMREG1        (RDA_IRQ_BASE + 18)
#define RDA_IRQ_USB            (RDA_IRQ_BASE + 19)
#define RDA_IRQ_DMC            (RDA_IRQ_BASE + 20)
#define RDA_IRQ_DMA            (RDA_IRQ_BASE + 21)
#define RDA_IRQ_CAMERA         (RDA_IRQ_BASE + 22)
#define RDA_IRQ_LCDC          (RDA_IRQ_BASE + 23)
#define RDA_IRQ_GPU            (RDA_IRQ_BASE + 24)
#define RDA_IRQ_RESERVE     (RDA_IRQ_BASE + 25)
#define RDA_IRQ_VOC            (RDA_IRQ_BASE + 26)
#define RDA_IRQ_VOC2           (RDA_IRQ_BASE + 27)
#define RDA_IRQ_AUIFC0         (RDA_IRQ_BASE + 28)
#define RDA_IRQ_AUIFC1         (RDA_IRQ_BASE + 29)
#define RDA_IRQ_CFG_RESERVE   (RDA_IRQ_BASE + 30)
#define RDA_IRQ_PAGESPY_DMC  (RDA_IRQ_BASE + 31)
#define RDA_CFG_RESRVE_29     (RDA_IRQ_BASE + 32)
#define RDA_IRQ_TIMER2         (RDA_IRQ_BASE + 33)
#define RDA_IRQ_TIMEROS2       (RDA_IRQ_BASE + 34)
#define RDA_IRQ_TIMER3         (RDA_IRQ_BASE + 35)
#define RDA_IRQ_TIMEROS3       (RDA_IRQ_BASE + 36)
#define RDA_IRQ_PMU            (RDA_IRQ_BASE + 37)
#define RDA_IRQ_GPMMU          (RDA_IRQ_BASE + 38)
#define RDA_IRQ_GP             (RDA_IRQ_BASE + 39)
#define RDA_IRQ_PPMMU0         (RDA_IRQ_BASE + 40)
#define RDA_IRQ_PP0            (RDA_IRQ_BASE + 41)
#define RDA_IRQ_NIRQ   (RDA_IRQ_BASE + 42)
#define RDA_IRQ_PAGE_DMC_FIQ       (RDA_IRQ_BASE + 43)
#define RDA_IRQ_SHA      (RDA_IRQ_BASE + 44)
#define RDA_IRQ_AES     (RDA_IRQ_BASE + 45)
#define RDA_IRQ_VPU      (RDA_IRQ_BASE + 46)
#define RDA_IRQ_JPEG      (RDA_IRQ_BASE + 47)
#define RDA_IRQ_CAMERA2        (RDA_IRQ_BASE + 48)
#define RDA_IRQ_GPIOE4           (RDA_IRQ_BASE + 49)
#define RDA_IRQ_PPMMU1         (RDA_IRQ_BASE + 50)
#define RDA_IRQ_PP01           (RDA_IRQ_BASE + 51)
#define RDA_IRQ_ETHMAC         (RDA_IRQ_BASE + 52)
#define RDA_IRQ_ISP_HSYNC      (RDA_IRQ_BASE + 53)
#define RDA_IRQ_USB2           (RDA_IRQ_BASE + 54)
#define RDA_IRQ_GOUDA          (RDA_IRQ_BASE + 55)
#define RDA_IRQ_UART4          (RDA_IRQ_BASE + 56)

#define RDA_IRQ_FIQ            (RDA_IRQ_BASE + 57)
#define RDA_IRQ_RESERVE_58     (RDA_IRQ_BASE + 58)
#define RDA_IRQ_RESERVE_59     (RDA_IRQ_BASE + 59)
#define RDA_IRQ_RESERVE_60     (RDA_IRQ_BASE + 60)
#define RDA_IRQ_RESERVE_61     (RDA_IRQ_BASE + 61)
#define RDA_IRQ_RESERVE_62     (RDA_IRQ_BASE + 62)
#define RDA_IRQ_RESERVE_63     (RDA_IRQ_BASE + 63)


#define NR_RDA_IRQS            (RDA_IRQ_BASE + 64)

/*
 * for every gpio bank, only 8 gpio pins can be input interrupt line
 */
#define RDA_GPIO_IRQ_START	(NR_RDA_IRQS)
#define	NR_GPIO_BANK_IRQS	8
#define NR_GPIO_IRQS		(NR_GPIO_BANK_IRQS * 4)
#define GPIO_IRQ_MASK		0xff //(bit0~7)

#define NR_IRQS                 (NR_RDA_IRQS + NR_GPIO_IRQS)

#endif /* __ASM_ARCH_IRQS_RDA8850E_H */
