#ifndef __RDA_GPIO_HW_H__
#define __RDA_GPIO_HW_H__

/*
 * we access invalid gpio reg, that will cause a oops;
 */
#define INVALID_GPIO_REG	(0x0)

#define RDA_GPIOA_REG(offs)		(RDA_GPIOA_BASE + (offs))
#define RDA_GPIOB_REG(offs)		(RDA_GPIOB_BASE + (offs))
#define RDA_GPIOD_REG(offs)		(RDA_GPIOD_BASE + (offs))
#define RDA_GPIOC_REG(offs)		(RDA_GPIOC_BASE + (offs))
#define RDA_GPIOE_REG(offs)		(RDA_GPIOE_BASE + (offs))

#define RDA_GPIO_OEN_VAL_A		IOMEM(RDA_GPIOA_REG(0x00))
#define RDA_GPIO_OEN_SET_OUT_A		IOMEM(RDA_GPIOA_REG(0x04))
#define RDA_GPIO_SET_IN_A		IOMEM(RDA_GPIOA_REG(0x08))
#define RDA_GPIO_VAL_A			IOMEM(RDA_GPIOA_REG(0x0c))
#define RDA_GPIO_SET_A			IOMEM(RDA_GPIOA_REG(0x10))
#define RDA_GPIO_CLR_A			IOMEM(RDA_GPIOA_REG(0x14))
#define RDA_GPIO_INT_CTRL_SET_A		IOMEM(RDA_GPIOA_REG(0x18))
#define RDA_GPIO_INT_CTRL_CLR_A		IOMEM(RDA_GPIOA_REG(0x1c))
#define RDA_GPIO_INT_CLR_A		IOMEM(RDA_GPIOA_REG(0x20))
#define RDA_GPIO_INT_STATUS_A		IOMEM(RDA_GPIOA_REG(0x24))


#define RDA_GPIO_OEN_VAL_B		IOMEM(RDA_GPIOB_REG(0x00))
#define RDA_GPIO_OEN_SET_OUT_B		IOMEM(RDA_GPIOB_REG(0x04))
#define RDA_GPIO_SET_IN_B		IOMEM(RDA_GPIOB_REG(0x08))
#define RDA_GPIO_VAL_B			IOMEM(RDA_GPIOB_REG(0x0c))
#define RDA_GPIO_SET_B			IOMEM(RDA_GPIOB_REG(0x10))
#define RDA_GPIO_CLR_B			IOMEM(RDA_GPIOB_REG(0x14))
#define RDA_GPIO_INT_CTRL_SET_B		IOMEM(RDA_GPIOB_REG(0x18))
#define RDA_GPIO_INT_CTRL_CLR_B		IOMEM(RDA_GPIOB_REG(0x1c))
#define RDA_GPIO_INT_CLR_B		IOMEM(RDA_GPIOB_REG(0x20))
#define RDA_GPIO_INT_STATUS_B		IOMEM(RDA_GPIOB_REG(0x24))

#define RDA_GPIO_OEN_VAL_C		IOMEM(RDA_GPIOC_REG(0x00))
#define RDA_GPIO_OEN_SET_OUT_C		IOMEM(RDA_GPIOC_REG(0x04))
#define RDA_GPIO_SET_IN_C		IOMEM(RDA_GPIOC_REG(0x08))
#define RDA_GPIO_VAL_C			IOMEM(RDA_GPIOC_REG(0x0c))
#define RDA_GPIO_SET_C			IOMEM(RDA_GPIOC_REG(0x10))
#define RDA_GPIO_CLR_C			IOMEM(RDA_GPIOC_REG(0x14))
#define RDA_GPIO_INT_CTRL_SET_C		IOMEM(RDA_GPIOC_REG(0x18))
#define RDA_GPIO_INT_CTRL_CLR_C		IOMEM(RDA_GPIOC_REG(0x1c))
#define RDA_GPIO_INT_CLR_C		IOMEM(RDA_GPIOC_REG(0x20))
#define RDA_GPIO_INT_STATUS_C		IOMEM(RDA_GPIOC_REG(0x24))

#define RDA_GPIO_OEN_VAL_D		IOMEM(RDA_GPIOD_REG(0x00))
#define RDA_GPIO_OEN_SET_OUT_D		IOMEM(RDA_GPIOD_REG(0x04))
#define RDA_GPIO_SET_IN_D		IOMEM(RDA_GPIOD_REG(0x08))
#define RDA_GPIO_VAL_D			IOMEM(RDA_GPIOD_REG(0x0c))
#define RDA_GPIO_SET_D			IOMEM(RDA_GPIOD_REG(0x10))
#define RDA_GPIO_CLR_D			IOMEM(RDA_GPIOD_REG(0x14))
#define RDA_GPIO_INT_CTRL_SET_D		IOMEM(RDA_GPIOD_REG(0x18))
#define RDA_GPIO_INT_CTRL_CLR_D		IOMEM(RDA_GPIOD_REG(0x1c))
#define RDA_GPIO_INT_CLR_D		IOMEM(RDA_GPIOD_REG(0x20))
#define RDA_GPIO_INT_STATUS_D		IOMEM(RDA_GPIOD_REG(0x24))

#define RDA_GPIO_OEN_VAL_E		IOMEM(RDA_GPIOE_REG(0x00))
#define RDA_GPIO_OEN_SET_OUT_E		IOMEM(RDA_GPIOE_REG(0x04))
#define RDA_GPIO_SET_IN_E		IOMEM(RDA_GPIOE_REG(0x08))
#define RDA_GPIO_VAL_E		IOMEM(RDA_GPIOE_REG(0x0c))
#define RDA_GPIO_SET_E			IOMEM(RDA_GPIOE_REG(0x10))
#define RDA_GPIO_CLR_E			IOMEM(RDA_GPIOE_REG(0x14))
#define RDA_GPIO_INT_CTRL_SET_E		IOMEM(RDA_GPIOE_REG(0x18))
#define RDA_GPIO_INT_CTRL_CLR_E		IOMEM(RDA_GPIOE_REG(0x1c))
#define RDA_GPIO_INT_CLR_E		IOMEM(RDA_GPIOE_REG(0x20))
#define RDA_GPIO_INT_STATUS_E		IOMEM(RDA_GPIOE_REG(0x24))

#define RDA_GPIO_OEN_VAL_GPO1		INVALID_GPIO_REG
#define RDA_GPIO_OEN_SET_OUT_GPO1	INVALID_GPIO_REG
#define RDA_GPIO_SET_IN_GPO1		INVALID_GPIO_REG
#define RDA_GPIO_VAL_GPO1		INVALID_GPIO_REG
#define RDA_GPIO_SET_GPO1		IOMEM(RDA_GPIOA_REG(0x30))
#define RDA_GPIO_CLR_GPO1		IOMEM(RDA_GPIOA_REG(0x34))
#define RDA_GPIO_INT_CTRL_SET_GPO1	INVALID_GPIO_REG
#define RDA_GPIO_INT_CTRL_CLR_GPO1	INVALID_GPIO_REG
#define RDA_GPIO_INT_CLR_GPO1		INVALID_GPIO_REG
#define RDA_GPIO_INT_STATUS_GPO1	INVALID_GPIO_REG

#endif
